version: "2"
services:
  minio:
    container_name: myminio
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /export
    networks:
      - minio-lambda-net

networks:
  minio-lambda-net:
    external: true